name: Linux Build

on:
  pull_request:
  push:
    paths-ignore:
      - '.github/workflows/macos-build.yml'
      - '.github/workflows/msys2-build.yml'
      - '.github/workflows/windows-build.yml'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        confs:
        - { mode: debug, archive: yes }
        - { mode: release, archive: yes }
    uses: ./.github/workflows/linux-base.yml
    with:
      target: ${{ matrix.target }}
